name: Java CI with Gradle (Kotlin)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Check Java style
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessJavaCheck

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test

      - name: Run tests with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            **/build/reports
